version: '3.7'
services:
  web:
    build: .
    command:
      - bash
      - -c
      - 'if [ ! -d "/app/node_modules" ]; then yarn install; fi && yarn start'
    ports:
      - 9000:9000
      - 9229:9229
    volumes:
      - .:/app

  flow:
    build: .
    command: yarn flow server
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - web
