orbs:
  node: circleci/node@4.5.0

version: 2.1

executors:
  workspace:
    docker:
      - image: cimg/node:14.17

jobs:
  anything:
    executor: workspace
    steps:
      - run: |
          node --version
          yarn --version

workflows:
  production:
    jobs:
      - anything:
          filters:
            branches:
              only: reserved
