orbs:
  node: circleci/node@4.5.0

version: 2.1

executors:
  workspace:
    docker:
      - image: cimg/node:14.17

commands:
  prepare:
    steps:
      - checkout
      - run: |
          node --version
          yarn --version
      - node/install-packages:
          pkg-manager: yarn

  build:
    steps:
      - run: yarn build

jobs:
  build-and-release:
    executor: workspace
    steps:
      - prepare
      - build

  build:
    executor: workspace
    steps:
      - prepare
      - build

workflows:
  production:
    jobs:
      - build-and-release:
          filters:
            branches:
              only: master

  development:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - master
                - /release-.*/
                - /v\d+/
