name: Deploy github pages

on:
  push:
    branches:
      - develop

permissions:
  contents: write

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20
      - run: pnpm install
      - run: npm run build
      # TODO: Move to lib
      - run: |
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]
      - run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
